syntax on
filetype plugin indent on
set number
set mouse=a
let NERDTreeShowHidden=1

" Nerdtree
autocmd StdinReadPre * let s:std_in=1
autocmd VimEnter * if argc() == 0 && !exists("s:std_in") | NERDTree | endif
map <C-n> :NERDTreeToggle<CR>
let g:NERDTreeDirArrowExpandable = 'v'
let g:NERDTreeDirArrowCollapsible = '>'

"lightline
set laststatus=2
set noshowmode
let g:lightline = {
      \ 'colorscheme': 'powerline',
      \ 'active': {
      \   'left': [ [ 'mode', 'paste' ],
      \             [ 'readonly', 'filename', 'modified' ] ],
      \   'right':[ [ 'lineinfo' ],
      \              [ 'percent' ],
      \              [ 'filetype', 'gitbranch'] ]
      \ },
      \ 'component_function': {
      \   'gitbranch': 'fugitive#head'
      \ },
      \ }

"Autocompleted
set omnifunc=syntaxcomplete#Complete
set completeopt=longest,menuone
